spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SocialMedia;encrypt=true;trustServerCertificate=true
spring.datasource.username=sm_user
spring.datasource.password=StrongPass@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# NOTE: Using 'update' is convenient for development to create tables automatically.
# For production, set this to 'none' and manage schema with migrations (Flyway/Liquibase).

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Upload directory
upload.dir=uploads

# Multipart file upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

# JWT
app.jwt.secret=0123456789abcdef0123456789abcdef
app.jwt.expMinutes=120